WATCHLIST = ["AAPL","MSFT","GOOGL","AMZN","TSLA","NVDA"]
REQUEST_INTERVAL_SECONDS = 15
RATE_LIMIT_RETRY_SECONDS = 60
REQUEST_CONNECT_TIMEOUT_SECONDS = 5
REQUEST_READ_TIMEOUT_SECONDS = 45
MAX_REQUEST_RETRIES = 4
RETRY_BACKOFF_BASE_SECONDS = 2
RETRY_BACKOFF_MAX_SECONDS = 30
